image: node:alpine

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | sh
  - yarn install --cache-folder .yarn-cache --no-progress --no-emoji

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - yarn run test

build:
  stage: build
  script:
    - yarn run build

pages:
  stage: deploy
  image: node:alpine
  script:
    - yarn run build
  artifacts:
    paths:
      - build
  