image: node

variables:
  DOCKER_DRIVER: overlay
  GITLAB_REGISTRY: registry.gitlab.com
  REPO_REGISTRY: registry.gitlab.com/olyverdev/cloudinary-client
  CONTAINER_NAME: cloudinary-client

services:
  - docker:dind

before_script:
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install --cache-folder .yarn-cache --no-progress --no-emoji

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - yarn run test

build_package: &build_package
  stage: build
  script:
    - yarn run build

pages:
  stage: deploy
  environment: staging
  script:
    - yarn run build
  artifacts:
    paths:
      - public

build_image:
  <<: *build_package
  stage: build
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $GITLAB_REGISTRY
  script:
    - docker build -t $REPO_REGISTRY .
    - docker push $REPO_REGISTRY
  only:
    - master
