image: node:alpine

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - test
  - build

test:
  stage: test
  script:
    - yarn run test

build:
  stage: build
  script:
    - yarn run build
