image: node

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install --cache-folder .yarn-cache --no-progress --no-emoji

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - yarn run test

build_package: &build_package
  stage: build
  image: node
  script:
    - yarn run build

pages:
  stage: deploy
  environment: staging
  image: node
  script:
    - yarn run build
  artifacts:
    paths:
      - public

# build_artifact:
#   <<: *build_package
#   stage: build
#   image: docker:latest
#   script:
#     - docker login registry.gitlab.com
#     - docker build -t registry.gitlab.com/olyverdev/cloudinary-client .
#     - docker push registry.gitlab.com/olyverdev/cloudinary-client
#   only:
#     - master
