image: node:alpine

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - yarn install --cache-folder .yarn-cache --no-progress --no-emoji

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - yarn run test

build:
  stage: build
  script:
    - yarn run build

pages:
  stage: deploy
  environment: staging
  image: node:alpine
  script:
    - yarn run build
  artifacts:
    paths:
      - public

build_prod:
  stage: build
  image: docker:latest
  script:
    - yarn run build
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/olyverdev/cloudinary-client .
    - docker push registry.gitlab.com/olyverdev/cloudinary-client
  only:
    - master